# 用户user
CREATE TABLE `user`(
	`id` int(11) NOT NULL AUTO_INCREMENT COMMENT "用户id",
	`password` VARCHAR(128) NOT NULL DEFAULT '' COMMENT "用户密码",
	`name` VARCHAR(128) NOT NULL DEFAULT '' COMMENT "用户昵称",
	`gender` TINYINT(4) NOT NULL DEFAULT '0' COMMENT "用户性别",
	`age` INT(11) NOT NULL DEFAULT '0' COMMENT "用户年龄",
	`portrait` VARCHAR(128) NOT NULL DEFAULT '' COMMENT "用户头像",
	PRIMARY KEY(`id`)
) ENGINE=INNODB DEFAULT CHARSET=utf8 COMMENT "用户表";